fix vision models to use the correct device
pytorch/benchmark pull request #274
Opened 2021-02-23 04:05 UTC by Krovatkin

fix vision models to use the correct device

2021-02-23 19:59 UTC, asuhan approved these changes

2021-02-23 20:17 UTC, wconstab requested changes
Can you also add an assert as @asuhan had described?  I'd like to enforce this so it doesn't happen again.  

I guess it's not possible to do this outside of the benchmark code as things are structured now.  What's the penalty of adding one assert into every measurement?  should be a wash, i guess?

2021-02-23 20:31 UTC, Krovatkin commented
> I guess it's not possible to do this outside of the benchmark code as things are structured now. What's the penalty of adding one assert into every measurement? should be a wash, i guess?

we should follow up in another PR since

1. for non-vision models, it's a bit tricky to get at models' inputs, let alone models' outputs.
2. I'm thinking we could do a little bit restructuring to make freezing a little bit easier and hopefully this will let us keep asserts outside.
3. If we decide to do asserts, I'd still like to do measurements to make sure we aren't affecting a score too much.

2021-02-24 00:25 UTC, wconstab approved these changes
ok I will not block this then.

2021-02-24 17:33 UTC, merged